### ISSUE TITLE
 Always call R&R API false

### ISSUE THREAD

**Issue by flyingroach** [watson-developer-cloud/conversation-enhanced#46]
Hello, Thanks for your sharing the code and i could enable to deploy with my own conversation locally.
I have a issue to call R&R API
Whatever, i input i am not enable call the API Rertive and Rank, which always return false.
I have setup the rankID,Cluster ID etc to the server.env file, but it not works.
If someone could tell me what to do to call my R&R API with my own conversation?

Thanks so much!

**Comment by dgterry** [comment]
Hello,
It sounds like you are wondering how you can have your own conversation workspace tell the app when to call R&R? 

The way we do it in this app is to set a flag called call_retrieve_and_rank to true in the conversation workspace's dialog nodes. For example here is one of the dialog node's in this app

```
{
  "output": {
    "text": "That question is out of scope for this application, take a look at the Conversation Enhanced application to handle questions like these."
  },
  "context": {
    "call_retrieve_and_rank": true
  }
}
```

The app then looks for the flag and calls R&R if it exists and is set to true.  See: 
https://github.com/watson-developer-cloud/conversation-enhanced/blob/master/src/main/java/com/ibm/watson/apis/conversation_enhanced/rest/ProxyResource.java#L125

I should point out that after this call is made it is important to have the app reset the flag to false before any further calls to Conversation are made.  If this is not done then the app will simply always see the flag as true (even if Convo is not directly setting it) and always call R&R. 

If I misunderstood your questions please just reply here.

**Comment by flyingroach** [comment]
Well, Thanks Dave.  That is the point i want ask. Thank you!
I just thought i need to replace some of my R&R source like file4.json,training.csv etc.
So,just need  the conversation's node got the input of flag is true and then the R&R API.query will implement of my owner R&R ?

**Comment by dgterry** [comment]
`So,just need the conversation's node got the input of flag is true and then the R&R API.query will implement of my owner R&R ?` that's essentially all you need to do in your conversational dialog nodes to tell the app to call R&R.  The rest would be in the app itself, setting the appropriate environment variables so that the application knows which services to call, and possibly making some small tweaks to the code.

To do that you can follow this section, https://github.com/watson-developer-cloud/conversation-enhanced#running-locally
that will get the correct credentials for your conversation and R&R services into your local app.  Setting the WORKSPACE_ID will have the app communicate with your custom workspace.

As for R&R, here are the ENVs I would set...they are hopefully pretty self explanatory but I'll provide a little info.

CLUSTER_ID should be the ID of your cluster, you should be able to get it from the application logs or R&R tooling displays it as well
RANKER_ID should be set to the ID of the ranker you want to use, you can get it from certain areas in the tooling or the app logs
COLLECTION_NAME should be the name of the collection you are using, you can see it when you login to the R&R tooling

Let me know if you have trouble setting the ENVs, it's the same way you set the WORKSPACE_ID when you created the app.

I'm hoping that improves things.  If that doesn't get you 100% of the way I would suggest looking at this method:

https://github.com/watson-developer-cloud/conversation-enhanced/blob/master/src/main/java/com/ibm/watson/apis/conversation_enhanced/retrieve_and_rank/Query.java#L104

and examining the response from R&R. It might be that your schema fields are slightly off from what we are using and you need to look at this query() method and its callers to alter the mapping from what R&R returns to what the UI expects.

**Comment by flyingroach** [comment]
Thanks Dave. and I know how to use the flag. It is very clear.
I am not succeed to see what i want because i have no a trained Rank ID which need too many questions to train. Every time i tried to use the collection or the Rank-ID the server will be  down.
It is very well for me to have a test if i could use the rank ID =untrained retrieve service.
I think your method will work when i finished a trained Rank ID. Thanks very much!!

**Comment by dgterry** [comment]
Hello,
It is possible to use the R&R service without the ranker.  The tricky thing is that the app expects it to be there. You could potentially disable its use of the ranker.  One area to start looking in would be
https://github.com/watson-developer-cloud/conversation-enhanced/blob/master/src/main/java/com/ibm/watson/apis/conversation_enhanced/retrieve_and_rank/Query.java#L116
you could comment out line 117 so it won't include a ranker in the call to R&R. There might be other areas you need to find and disable but I'd start here.

**Comment by flyingroach** [comment]
Hello Dave.I will try.  Thank you for your help!
