### ISSUE TITLE
Error 404:java.io.FileNotFoundException: SRVE0190E: File not found......

### ISSUE THREAD

**Issue by henry921630** [watson-developer-cloud/conversation-enhanced#47]
Hi, I got this error message as this pic: http://imgur.com/a/JaRqF
I don't know what this means. How can I solve it?

I can just ignore this error message and the Conversation still works well. But when Retrieve and Rank be triggered, there will be  just a loading icon without any response until I enter next message. 

This error occurs both on http://conversation-enhanced.mybluemix.net/ and my own deployment.
I've been trying hard to solve this problem but in vain.
Please help me, thanks!

**Comment by ashleylord8** [comment]
@henry921630 

Hi, we feel that this issue is occurring because the language set in your browser is non-English. In the meantime as we try to solve this issue, you could fix it for yourself by providing a translated zh.json file under the folder, `conversation-enhanced/src/main/webapp/locale` (or just copy the english one, `en.json`, in there as a `zh.json` file), or setting your browser language to English.

**Comment by dgterry** [comment]
resolving, this should be fixed by https://github.com/watson-developer-cloud/conversation-enhanced/pull/56
