### ISSUE TITLE
Proxy configure

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-enhanced#49]
Hi Davi, good morning.

![erro barramento proxy](https://cloud.githubusercontent.com/assets/23122214/20264255/bf130e4a-aa51-11e6-837e-930b7ca87c98.JPG)

Where can I enter my proxy data?
Because they had to free me for general access to the internet instead of going through the proxy, I would like to know where I can add the settings.

**Comment by dgterry** [comment]
hello,

I would recommend you ask this question here: https://developer.ibm.com/answers/topics/watson-conversation/

It might be that you just need to specify a different endpoint URL so that the Conversation object you create here: https://github.com/watson-developer-cloud/conversation-enhanced/blob/master/src/main/java/com/ibm/watson/apis/conversation_enhanced/rest/ProxyResource.java#L111
sends calls through your proxy instead of directly to Conversation.

**Comment by dpowell1** [comment]
How do we use the ProxyResource to configure the proxy? Does ProxyResource take in the command line arguments from the JVM or do we have to manually set the host, port, etc. in ProxyResource?

FYI, the link changed to <https://github.com/watson-developer-cloud/conversation-with-discovery/blob/master/src/main/java/com/ibm/watson/apis/conversation_with_discovery/rest/ProxyResource.java>
